#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_yum(opsys, conf, conf_dir, plugins_dir):
    target_dir = plugins_dir + "/%d" % conf["interval"] # Interval for async execution
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
    if conf:
        try:
            shutil.copy2(cmk.paths.local_agents_dir + "/plugins/yum", target_dir + "/yum")
        except:
            # see https://github.com/HenriWahl/checkmk-agent-plugin-yum/issues/5#issuecomment-311061650

            # in CheckMK v 1.6 cmk.paths is changed to cmk.utils.paths
            shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/yum", target_dir + "/yum")
    os.chmod(target_dir + "/yum", 0755)

bakery_info["yum"] = {
    "bake_function" : bake_yum,
    "os"            : [ "linux", ],
}
